/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klinik_pbo;

import dao.RuanganDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Ruangan;

/**
 *
 * @author avvjelly
 */
public class DaftarRuanganAdmin extends javax.swing.JFrame {
    private void tampilkanDataRuangan() {
    List<Ruangan> daftar = RuanganDAO.getAllRuangan();
    DefaultTableModel model = (DefaultTableModel) TabelDaftarRuangan.getModel();
    model.setRowCount(0); // Bersihkan isi tabel

    for (Ruangan r : daftar) {
        Object[] row = {
            r.getIdRuangan(),
            r.getNamaRuangan(),
            r.getLantai(),
            r.getKapasitas()
        };
        model.addRow(row);
    }
}


    /**
     * Creates new form DaftarRuanganAdmin
     */
    public DaftarRuanganAdmin() {
        initComponents();
        tampilkanDataRuangan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtamaDaftarRuangan = new javax.swing.JPanel();
        PanelSidebarAdmin2 = new javax.swing.JPanel();
        ButtonDashboard = new javax.swing.JButton();
        ButtonDaftarPasien = new javax.swing.JButton();
        ButtonDaftarDokter = new javax.swing.JButton();
        ButtonDaftarObat = new javax.swing.JButton();
        ButtonDaftarRuangan = new javax.swing.JButton();
        ButtonPendaftaranPasien = new javax.swing.JButton();
        ButtonPendaftaranDokter = new javax.swing.JButton();
        ButtonPendaftaranObat = new javax.swing.JButton();
        ButtonJadwalDokter = new javax.swing.JButton();
        ButtonResepPasien = new javax.swing.JButton();
        ButtonLogout = new javax.swing.JButton();
        LabelDaftarRuangan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDaftarRuangan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelUtamaDaftarRuangan.setPreferredSize(new java.awt.Dimension(800, 500));

        PanelSidebarAdmin2.setBackground(new java.awt.Color(0, 51, 102));
        PanelSidebarAdmin2.setPreferredSize(new java.awt.Dimension(200, 500));

        ButtonDashboard.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonDashboard.setText("Dashboard");
        ButtonDashboard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDashboardActionPerformed(evt);
            }
        });

        ButtonDaftarPasien.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonDaftarPasien.setText("Daftar Pasien");
        ButtonDaftarPasien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDaftarPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarPasienActionPerformed(evt);
            }
        });

        ButtonDaftarDokter.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonDaftarDokter.setText("Daftar Dokter");
        ButtonDaftarDokter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDaftarDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarDokterActionPerformed(evt);
            }
        });

        ButtonDaftarObat.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonDaftarObat.setText("Daftar Obat");
        ButtonDaftarObat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDaftarObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarObatActionPerformed(evt);
            }
        });

        ButtonDaftarRuangan.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonDaftarRuangan.setText("Daftar Ruangan");
        ButtonDaftarRuangan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ButtonPendaftaranPasien.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonPendaftaranPasien.setText("Pendaftaran Pasien");
        ButtonPendaftaranPasien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonPendaftaranPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPendaftaranPasienActionPerformed(evt);
            }
        });

        ButtonPendaftaranDokter.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonPendaftaranDokter.setText("Pendaftaran Dokter");
        ButtonPendaftaranDokter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonPendaftaranDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPendaftaranDokterActionPerformed(evt);
            }
        });

        ButtonPendaftaranObat.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonPendaftaranObat.setText("Pendaftaran Obat");
        ButtonPendaftaranObat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonPendaftaranObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPendaftaranObatActionPerformed(evt);
            }
        });

        ButtonJadwalDokter.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonJadwalDokter.setText("Jadwal Dokter");
        ButtonJadwalDokter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonJadwalDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonJadwalDokterActionPerformed(evt);
            }
        });

        ButtonResepPasien.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonResepPasien.setText("Resep Pasien");
        ButtonResepPasien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonResepPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResepPasienActionPerformed(evt);
            }
        });

        ButtonLogout.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonLogout.setText("Logout");
        ButtonLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSidebarAdmin2Layout = new javax.swing.GroupLayout(PanelSidebarAdmin2);
        PanelSidebarAdmin2.setLayout(PanelSidebarAdmin2Layout);
        PanelSidebarAdmin2Layout.setHorizontalGroup(
            PanelSidebarAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSidebarAdmin2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelSidebarAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonDaftarPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDaftarDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDaftarObat, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDaftarRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPendaftaranPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPendaftaranDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPendaftaranObat, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonJadwalDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonResepPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PanelSidebarAdmin2Layout.setVerticalGroup(
            PanelSidebarAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSidebarAdmin2Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(ButtonDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarPasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarDokter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarObat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarRuangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPendaftaranPasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPendaftaranDokter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPendaftaranObat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonJadwalDokter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonResepPasien)
                .addGap(34, 34, 34)
                .addComponent(ButtonLogout)
                .addContainerGap(1833, Short.MAX_VALUE))
        );

        LabelDaftarRuangan.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        LabelDaftarRuangan.setText("Daftar Ruangan");

        TabelDaftarRuangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Ruangan", "Nama Ruangan", "Lantai", "Kapasitas"
            }
        ));
        jScrollPane1.setViewportView(TabelDaftarRuangan);

        javax.swing.GroupLayout PanelUtamaDaftarRuanganLayout = new javax.swing.GroupLayout(PanelUtamaDaftarRuangan);
        PanelUtamaDaftarRuangan.setLayout(PanelUtamaDaftarRuanganLayout);
        PanelUtamaDaftarRuanganLayout.setHorizontalGroup(
            PanelUtamaDaftarRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaDaftarRuanganLayout.createSequentialGroup()
                .addComponent(PanelSidebarAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelUtamaDaftarRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUtamaDaftarRuanganLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelDaftarRuangan)
                        .addGap(197, 197, 197))
                    .addGroup(PanelUtamaDaftarRuanganLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        PanelUtamaDaftarRuanganLayout.setVerticalGroup(
            PanelUtamaDaftarRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaDaftarRuanganLayout.createSequentialGroup()
                .addComponent(PanelSidebarAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 2327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelUtamaDaftarRuanganLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(LabelDaftarRuangan)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelUtamaDaftarRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelUtamaDaftarRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDashboardActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini (DaftarPasienAdmin)
        this.dispose();

        // 2. Buka form DashboardAdmin
        DashboardAdmin dashboard = new DashboardAdmin();
        dashboard.setVisible(true);
    }//GEN-LAST:event_ButtonDashboardActionPerformed

    private void ButtonDaftarPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarPasienActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini (DaftarPasienAdmin)
        this.dispose();

        // 2. Buka form DaftarPasien
        DaftarPasienAdmin daftarpasien = new DaftarPasienAdmin();
        daftarpasien.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarPasienActionPerformed

    private void ButtonDaftarDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarDokterActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini (DaftarPasienAdmin)
        this.dispose();

        // 2. Buka form DaftarPasien
        DaftarDokterAdmin daftardokter = new DaftarDokterAdmin();
        daftardokter.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarDokterActionPerformed

    private void ButtonDaftarObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarObatActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
    this.dispose();
    
    // 2. Buka form 
    DaftarObatAdmin daftarobat = new DaftarObatAdmin();
    daftarobat.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarObatActionPerformed

    private void ButtonPendaftaranPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPendaftaranPasienActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
    this.dispose();
    
    // 2. Buka form 
    PendaftaranPasienAdmin pendaftarpasien = new PendaftaranPasienAdmin();
    pendaftarpasien.setVisible(true);
    }//GEN-LAST:event_ButtonPendaftaranPasienActionPerformed

    private void ButtonPendaftaranDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPendaftaranDokterActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        PendaftaranDokterAdmin daftardokter = new PendaftaranDokterAdmin();
        daftardokter.setVisible(true);
    }//GEN-LAST:event_ButtonPendaftaranDokterActionPerformed

    private void ButtonPendaftaranObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPendaftaranObatActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        PendaftaranObatAdmin daftarobat = new PendaftaranObatAdmin();
        daftarobat.setVisible(true);
    }//GEN-LAST:event_ButtonPendaftaranObatActionPerformed

    private void ButtonJadwalDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonJadwalDokterActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        JadwalDokterAdmin daftarjadwal = new JadwalDokterAdmin();
        daftarjadwal.setVisible(true);
    }//GEN-LAST:event_ButtonJadwalDokterActionPerformed

    private void ButtonResepPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResepPasienActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        ResepPasienAdmin daftarresep = new ResepPasienAdmin();
        daftarresep.setVisible(true);
    }//GEN-LAST:event_ButtonResepPasienActionPerformed

    private void ButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogoutActionPerformed
        // TODO add your handling code here:
        // Tampilkan dialog konfirmasi
    int pilihan = JOptionPane.showConfirmDialog(this, 
                    "Apakah Anda yakin ingin logout?", 
                    "Konfirmasi Logout", 
                    JOptionPane.YES_NO_OPTION);

    // Jika pengguna memilih "Yes"
    if (pilihan == JOptionPane.YES_OPTION) {
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form login
        Login login = new Login();
        login.setVisible(true);
      }
    }//GEN-LAST:event_ButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarRuanganAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarRuanganAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarRuanganAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarRuanganAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarRuanganAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDaftarDokter;
    private javax.swing.JButton ButtonDaftarObat;
    private javax.swing.JButton ButtonDaftarPasien;
    private javax.swing.JButton ButtonDaftarRuangan;
    private javax.swing.JButton ButtonDashboard;
    private javax.swing.JButton ButtonJadwalDokter;
    private javax.swing.JButton ButtonLogout;
    private javax.swing.JButton ButtonPendaftaranDokter;
    private javax.swing.JButton ButtonPendaftaranObat;
    private javax.swing.JButton ButtonPendaftaranPasien;
    private javax.swing.JButton ButtonResepPasien;
    private javax.swing.JLabel LabelDaftarRuangan;
    private javax.swing.JPanel PanelSidebarAdmin2;
    private javax.swing.JPanel PanelUtamaDaftarRuangan;
    private javax.swing.JTable TabelDaftarRuangan;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
