/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klinik_pbo;

import javax.swing.table.DefaultTableModel;
import dao.JadwalPraktikDAO;
import dao.UserDAO;
import model.JadwalPraktik;
import klinik_pbo.koneksi;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.User;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author avvjelly
 */
public class DashboardAdmin extends javax.swing.JFrame {
    DashboardService service = new DashboardService(); // service buat ambil data

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        tampilkanJadwalPraktik();
        tampilkanDaftarUser();

        LabelAngkaPasien.setText(String.valueOf(service.getJumlahPasien()));
        LabelAngkaDokter.setText(String.valueOf(service.getJumlahDokter()));
        LabelAngkaRuangan.setText(String.valueOf(service.getJumlahRuangan()));
        
        // Set the frame to be maximized
        setExtendedState(javax.swing.JFrame.MAXIMIZED_HORIZ);
    }

    private void tampilkanDaftarUser() {
        DefaultTableModel model = new DefaultTableModel(
                new String[]{"ID User", "Username", "Password", "Role"},
                0
        );

        List<User> users = UserDAO.getAllUsers();
        for (User u : users) {
            model.addRow(new Object[]{
                u.getIdUser(),
                u.getUsername(),
                u.getPassword(),
                u.getRole()
            });
        }
        TabelDaftarUser.setModel(model);
    }

    private void tampilkanJadwalPraktik() {
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID Jadwal", "Hari", "Jam Mulai", "Jam Berakhir"}, 0);
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/klinik_db", "root", "");
            JadwalPraktikDAO dao = new JadwalPraktikDAO(conn);
            List<JadwalPraktik> list = dao.getAllJadwal();
            for (JadwalPraktik jp : list) {
                model.addRow(new Object[]{
                    jp.getIdJadwal(),
                    jp.getHari(),
                    jp.getJamMulai(),
                    jp.getJamBerakhir()
                });
            }
            TabelJadwalPraktik.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JPanel();
        PanelSidebarAdmin = new javax.swing.JPanel();
        ButtonDashboard = new javax.swing.JButton();
        ButtonDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard.png"))); // ADD THIS LINE
        ButtonDaftarPasien = new javax.swing.JButton();
        ButtonDaftarPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/daftar_pasien.png"))); // ADD THIS LINE
        ButtonDaftarDokter = new javax.swing.JButton();
        ButtonDaftarDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/daftar_dokter.png"))); // ADD THIS LINE
        ButtonDaftarObat = new javax.swing.JButton();
        ButtonDaftarObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/daftar_obat.png"))); // ADD THIS LINE
        ButtonDaftarRuangan = new javax.swing.JButton();
        ButtonDaftarRuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ruangan.png"))); // ADD THIS LINE
        ButtonPendaftaranPasien = new javax.swing.JButton();
        ButtonPendaftaranPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pendaftaran_pasien.png"))); // ADD THIS LINE
        ButtonPendaftaranDokter = new javax.swing.JButton();
        ButtonPendaftaranDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pendaftaran_dokter.png"))); // ADD THIS LINE
        ButtonPendaftaranObat = new javax.swing.JButton();
        ButtonPendaftaranObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pendaftaran_obat.png"))); // ADD THIS LINE
        ButtonJadwalDokter = new javax.swing.JButton();
        ButtonJadwalDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jadwal_dokter.png"))); // ADD THIS LINE
        ButtonResepPasien = new javax.swing.JButton();
        ButtonResepPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/resep.png"))); // ADD THIS LINE
        ButtonLogout = new javax.swing.JButton();
        ButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // ADD THIS LINE
        LabelTulisanDashboard = new javax.swing.JLabel();
        PanelAdminDashboard1 = new javax.swing.JPanel();
        LabelAngkaPasien = new javax.swing.JLabel();
        LabelPasienDashboard = new javax.swing.JLabel();
        PanelAdminDashboard2 = new javax.swing.JPanel();
        LabelDokterDashboard = new javax.swing.JLabel();
        LabelAngkaDokter = new javax.swing.JLabel();
        PanelAdminDashboard4 = new javax.swing.JPanel();
        LabelRuangDashboard = new javax.swing.JLabel();
        LabelAngkaRuangan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelJadwalPraktik = new javax.swing.JTable();
        LabelJadwal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelDaftarUser = new javax.swing.JTable();
        LabelDaftarUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard Admin - Sistem Informasi Klinik");

        PanelUtama.setBackground(new java.awt.Color(240, 240, 240)); // Light grey background
        PanelUtama.setPreferredSize(new java.awt.Dimension(1000, 700)); // Increased size for better layout

        PanelSidebarAdmin.setBackground(new java.awt.Color(0, 51, 102)); // Dark blue
        PanelSidebarAdmin.setPreferredSize(new java.awt.Dimension(220, 700)); // Wider sidebar

        ButtonDashboard.setBackground(new java.awt.Color(0, 102, 153)); // Slightly lighter blue for active
        ButtonDashboard.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 15)); // Bold and larger
        ButtonDashboard.setForeground(new java.awt.Color(255, 255, 255)); // White text
        ButtonDashboard.setText("Dashboard");
        ButtonDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15)); // Padding
        ButtonDashboard.setFocusPainted(false); // Remove focus border

        ButtonDaftarPasien.setBackground(new java.awt.Color(0, 51, 102));
        ButtonDaftarPasien.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonDaftarPasien.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDaftarPasien.setText("Daftar Pasien");
        ButtonDaftarPasien.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonDaftarPasien.setFocusPainted(false);
        ButtonDaftarPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarPasienActionPerformed(evt);
            }
        });

        ButtonDaftarDokter.setBackground(new java.awt.Color(0, 51, 102));
        ButtonDaftarDokter.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonDaftarDokter.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDaftarDokter.setText("Daftar Dokter");
        ButtonDaftarDokter.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonDaftarDokter.setFocusPainted(false);
        ButtonDaftarDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarDokterActionPerformed(evt);
            }
        });

        ButtonDaftarObat.setBackground(new java.awt.Color(0, 51, 102));
        ButtonDaftarObat.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonDaftarObat.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDaftarObat.setText("Daftar Obat");
        ButtonDaftarObat.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonDaftarObat.setFocusPainted(false);
        ButtonDaftarObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarObatActionPerformed(evt);
            }
        });

        ButtonDaftarRuangan.setBackground(new java.awt.Color(0, 51, 102));
        ButtonDaftarRuangan.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonDaftarRuangan.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDaftarRuangan.setText("Daftar Ruangan");
        ButtonDaftarRuangan.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonDaftarRuangan.setFocusPainted(false);
        ButtonDaftarRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarRuanganActionPerformed(evt);
            }
        });

        ButtonPendaftaranPasien.setBackground(new java.awt.Color(0, 51, 102));
        ButtonPendaftaranPasien.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonPendaftaranPasien.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPendaftaranPasien.setText("Pendaftaran Pasien");
        ButtonPendaftaranPasien.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonPendaftaranPasien.setFocusPainted(false);
        ButtonPendaftaranPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPendaftaranPasienActionPerformed(evt);
            }
        });

        ButtonPendaftaranDokter.setBackground(new java.awt.Color(0, 51, 102));
        ButtonPendaftaranDokter.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonPendaftaranDokter.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPendaftaranDokter.setText("Pendaftaran Dokter");
        ButtonPendaftaranDokter.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonPendaftaranDokter.setFocusPainted(false);
        ButtonPendaftaranDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPendaftaranDokterActionPerformed(evt);
            }
        });

        ButtonPendaftaranObat.setBackground(new java.awt.Color(0, 51, 102));
        ButtonPendaftaranObat.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonPendaftaranObat.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPendaftaranObat.setText("Pendaftaran Obat");
        ButtonPendaftaranObat.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonPendaftaranObat.setFocusPainted(false);
        ButtonPendaftaranObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPendaftaranObatActionPerformed(evt);
            }
        });

        ButtonJadwalDokter.setBackground(new java.awt.Color(0, 51, 102));
        ButtonJadwalDokter.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonJadwalDokter.setForeground(new java.awt.Color(255, 255, 255));
        ButtonJadwalDokter.setText("Jadwal Dokter");
        ButtonJadwalDokter.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonJadwalDokter.setFocusPainted(false);
        ButtonJadwalDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonJadwalDokterActionPerformed(evt);
            }
        });

        ButtonResepPasien.setBackground(new java.awt.Color(0, 51, 102));
        ButtonResepPasien.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonResepPasien.setForeground(new java.awt.Color(255, 255, 255));
        ButtonResepPasien.setText("Resep Pasien");
        ButtonResepPasien.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonResepPasien.setFocusPainted(false);
        ButtonResepPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResepPasienActionPerformed(evt);
            }
        });

        ButtonLogout.setBackground(new java.awt.Color(204, 0, 0)); // Red for logout
        ButtonLogout.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14));
        ButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogout.setText("Logout");
        ButtonLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonLogout.setFocusPainted(false);
        ButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSidebarAdminLayout = new javax.swing.GroupLayout(PanelSidebarAdmin);
        PanelSidebarAdmin.setLayout(PanelSidebarAdminLayout);
        PanelSidebarAdminLayout.setHorizontalGroup(
            PanelSidebarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSidebarAdminLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelSidebarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonResepPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonJadwalDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPendaftaranObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPendaftaranDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPendaftaranPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonDaftarRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonDaftarObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonDaftarDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonDaftarPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(ButtonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PanelSidebarAdminLayout.setVerticalGroup(
            PanelSidebarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSidebarAdminLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(ButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(ButtonDaftarPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarObat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(ButtonPendaftaranPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPendaftaranDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPendaftaranObat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonJadwalDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonResepPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE) // Pushed logout to bottom
                .addComponent(ButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        LabelTulisanDashboard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 30)); // Larger font
        LabelTulisanDashboard.setForeground(new java.awt.Color(0, 51, 102)); // Dark blue text
        LabelTulisanDashboard.setText("Selamat Datang di Dashboard Admin!");

        PanelAdminDashboard1.setBackground(new java.awt.Color(235, 250, 252));
        PanelAdminDashboard1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 153))); // Border
        PanelAdminDashboard1.setPreferredSize(new java.awt.Dimension(200, 100)); // Increased size

        LabelAngkaPasien.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 48)); // Larger font
        LabelAngkaPasien.setForeground(new java.awt.Color(0, 51, 102));
        LabelAngkaPasien.setText("5");

        LabelPasienDashboard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18));
        LabelPasienDashboard.setText("Jumlah Pasien");

        javax.swing.GroupLayout PanelAdminDashboard1Layout = new javax.swing.GroupLayout(PanelAdminDashboard1);
        PanelAdminDashboard1.setLayout(PanelAdminDashboard1Layout);
        PanelAdminDashboard1Layout.setHorizontalGroup(
            PanelAdminDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminDashboard1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(PanelAdminDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminDashboard1Layout.createSequentialGroup()
                        .addComponent(LabelAngkaPasien)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminDashboard1Layout.createSequentialGroup()
                        .addComponent(LabelPasienDashboard)
                        .addGap(41, 41, 41))))
        );
        PanelAdminDashboard1Layout.setVerticalGroup(
            PanelAdminDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminDashboard1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelPasienDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelAngkaPasien)
                .addGap(16, 16, 16))
        );

        PanelAdminDashboard2.setBackground(new java.awt.Color(235, 250, 252));
        PanelAdminDashboard2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 153)));
        PanelAdminDashboard2.setPreferredSize(new java.awt.Dimension(200, 100));

        LabelDokterDashboard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18));
        LabelDokterDashboard.setText("Jumlah Dokter");

        LabelAngkaDokter.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 48));
        LabelAngkaDokter.setForeground(new java.awt.Color(0, 51, 102));
        LabelAngkaDokter.setText("5");

        javax.swing.GroupLayout PanelAdminDashboard2Layout = new javax.swing.GroupLayout(PanelAdminDashboard2);
        PanelAdminDashboard2.setLayout(PanelAdminDashboard2Layout);
        PanelAdminDashboard2Layout.setHorizontalGroup(
            PanelAdminDashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminDashboard2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(PanelAdminDashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminDashboard2Layout.createSequentialGroup()
                        .addComponent(LabelDokterDashboard)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminDashboard2Layout.createSequentialGroup()
                        .addComponent(LabelAngkaDokter)
                        .addGap(81, 81, 81))))
        );
        PanelAdminDashboard2Layout.setVerticalGroup(
            PanelAdminDashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminDashboard2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDokterDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelAngkaDokter)
                .addGap(16, 16, 16))
        );

        PanelAdminDashboard4.setBackground(new java.awt.Color(235, 250, 252));
        PanelAdminDashboard4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 153)));
        PanelAdminDashboard4.setPreferredSize(new java.awt.Dimension(200, 100));

        LabelRuangDashboard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18));
        LabelRuangDashboard.setText("Jumlah Ruangan");

        LabelAngkaRuangan.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 48));
        LabelAngkaRuangan.setForeground(new java.awt.Color(0, 51, 102));
        LabelAngkaRuangan.setText("5");

        javax.swing.GroupLayout PanelAdminDashboard4Layout = new javax.swing.GroupLayout(PanelAdminDashboard4);
        PanelAdminDashboard4.setLayout(PanelAdminDashboard4Layout);
        PanelAdminDashboard4Layout.setHorizontalGroup(
            PanelAdminDashboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminDashboard4Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(PanelAdminDashboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminDashboard4Layout.createSequentialGroup()
                        .addComponent(LabelRuangDashboard)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminDashboard4Layout.createSequentialGroup()
                        .addComponent(LabelAngkaRuangan)
                        .addGap(81, 81, 81))))
        );
        PanelAdminDashboard4Layout.setVerticalGroup(
            PanelAdminDashboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminDashboard4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelRuangDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelAngkaRuangan)
                .addGap(16, 16, 16))
        );

        TabelJadwalPraktik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Jadwal", "Hari", "Mulai", "Berakhir"
            }
        ));
        TabelJadwalPraktik.setRowHeight(25); // Increased row height
        TabelJadwalPraktik.getTableHeader().setFont(new Font("Franklin Gothic Medium", Font.BOLD, 12)); // Bold header
        jScrollPane1.setViewportView(TabelJadwalPraktik);

        LabelJadwal.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24));
        LabelJadwal.setForeground(new java.awt.Color(0, 51, 102));
        LabelJadwal.setText("Jadwal Praktik Dokter");

        TabelDaftarUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID User", "Username", "Password", "Role"
            }
        ));
        TabelDaftarUser.setRowHeight(25); // Increased row height
        TabelDaftarUser.getTableHeader().setFont(new Font("Franklin Gothic Medium", Font.BOLD, 12)); // Bold header
        jScrollPane2.setViewportView(TabelDaftarUser);

        LabelDaftarUser.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24));
        LabelDaftarUser.setForeground(new java.awt.Color(0, 51, 102));
        LabelDaftarUser.setText("Daftar Pengguna Sistem");

        javax.swing.GroupLayout PanelUtamaLayout = new javax.swing.GroupLayout(PanelUtama);
        PanelUtama.setLayout(PanelUtamaLayout);
        PanelUtamaLayout.setHorizontalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addComponent(PanelSidebarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTulisanDashboard)
                    .addGroup(PanelUtamaLayout.createSequentialGroup()
                        .addComponent(PanelAdminDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(PanelAdminDashboard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(PanelAdminDashboard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelUtamaLayout.createSequentialGroup()
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelJadwal))
                        .addGap(50, 50, 50)
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDaftarUser)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelUtamaLayout.setVerticalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSidebarAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LabelTulisanDashboard)
                .addGap(40, 40, 40)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelAdminDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelAdminDashboard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelAdminDashboard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelJadwal)
                    .addComponent(LabelDaftarUser))
                .addGap(18, 18, 18)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE) // Adjusted preferred size
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE) // Adjusted preferred size
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDaftarPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarPasienActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini 
        this.dispose();

        // 2. Buka form 
        DaftarPasienAdmin daftarpasien = new DaftarPasienAdmin();
        daftarpasien.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarPasienActionPerformed

    private void ButtonDaftarDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarDokterActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini 
        this.dispose();

        // 2. Buka form 
        DaftarDokterAdmin daftardokter = new DaftarDokterAdmin();
        daftardokter.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarDokterActionPerformed

    private void ButtonDaftarObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarObatActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form 
        DaftarObatAdmin daftarobat = new DaftarObatAdmin();
        daftarobat.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarObatActionPerformed

    private void ButtonDaftarRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarRuanganActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form 
        DaftarRuanganAdmin daftarruangan = new DaftarRuanganAdmin();
        daftarruangan.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarRuanganActionPerformed

    private void ButtonPendaftaranPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPendaftaranPasienActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form 
        PendaftaranPasienAdmin pendaftarpasien = new PendaftaranPasienAdmin();
        pendaftarpasien.setVisible(true);
    }//GEN-LAST:event_ButtonPendaftaranPasienActionPerformed

    private void ButtonPendaftaranDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPendaftaranDokterActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        PendaftaranDokterAdmin daftardokter = new PendaftaranDokterAdmin();
        daftardokter.setVisible(true);
    }//GEN-LAST:event_ButtonPendaftaranDokterActionPerformed

    private void ButtonPendaftaranObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPendaftaranObatActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        PendaftaranObatAdmin daftarobat = new PendaftaranObatAdmin();
        daftarobat.setVisible(true);
    }//GEN-LAST:event_ButtonPendaftaranObatActionPerformed

    private void ButtonJadwalDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonJadwalDokterActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        JadwalDokterAdmin daftarjadwal = new JadwalDokterAdmin();
        daftarjadwal.setVisible(true);
    }//GEN-LAST:event_ButtonJadwalDokterActionPerformed

    private void ButtonResepPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResepPasienActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        ResepPasienAdmin daftarresep = new ResepPasienAdmin();
        daftarresep.setVisible(true);
    }//GEN-LAST:event_ButtonResepPasienActionPerformed

    private void ButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogoutActionPerformed
        // TODO add your handling code here:
        // Tampilkan dialog konfirmasi
        int pilihan = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin logout?",
                "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION);

        // Jika pengguna memilih "Yes"
        if (pilihan == JOptionPane.YES_OPTION) {
            // 1. Tutup form saat ini
            this.dispose();

            // 2. Buka form login
            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_ButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDaftarDokter;
    private javax.swing.JButton ButtonDaftarObat;
    private javax.swing.JButton ButtonDaftarPasien;
    private javax.swing.JButton ButtonDaftarRuangan;
    private javax.swing.JButton ButtonDashboard;
    private javax.swing.JButton ButtonJadwalDokter;
    private javax.swing.JButton ButtonLogout;
    private javax.swing.JButton ButtonPendaftaranDokter;
    private javax.swing.JButton ButtonPendaftaranObat;
    private javax.swing.JButton ButtonPendaftaranPasien;
    private javax.swing.JButton ButtonResepPasien;
    private javax.swing.JLabel LabelAngkaDokter;
    private javax.swing.JLabel LabelAngkaPasien;
    private javax.swing.JLabel LabelAngkaRuangan;
    private javax.swing.JLabel LabelDaftarUser;
    private javax.swing.JLabel LabelDokterDashboard;
    private javax.swing.JLabel LabelJadwal;
    private javax.swing.JLabel LabelPasienDashboard;
    private javax.swing.JLabel LabelRuangDashboard;
    private javax.swing.JLabel LabelTulisanDashboard;
    private javax.swing.JPanel PanelAdminDashboard1;
    private javax.swing.JPanel PanelAdminDashboard2;
    private javax.swing.JPanel PanelAdminDashboard4;
    private javax.swing.JPanel PanelSidebarAdmin;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JTable TabelDaftarUser;
    private javax.swing.JTable TabelJadwalPraktik;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}