/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klinik_pbo;

import javax.swing.table.DefaultTableModel;
import dao.JadwalPraktikDAO;
import model.JadwalPraktik;
import klinik_pbo.koneksi;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author avvjelly
 */
public class DashboardDokter extends javax.swing.JFrame {

    // Anda mungkin perlu DashboardDokterService jika ingin menampilkan data dinamis di dashboard.
    // Untuk saat ini, saya akan menggunakan angka placeholder seperti DashboardAdmin.
    // DashboardService service = new DashboardService(); 

    private void tampilkanJadwalPraktik() {
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID Jadwal", "Hari", "Jam Mulai", "Jam Berakhir"}, 0);
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/klinik_db", "root", "");
            JadwalPraktikDAO dao = new JadwalPraktikDAO(conn);
            List<JadwalPraktik> list = dao.getAllJadwal();
            for (JadwalPraktik jp : list) {
                model.addRow(new Object[]{
                    jp.getIdJadwal(),
                    jp.getHari(),
                    jp.getJamMulai(),
                    jp.getJamBerakhir()
                });
            }
            TabelJadwalPraktik.setModel(model);
            conn.close(); // Close connection after use
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data jadwal praktik: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(DashboardDokter.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * Creates new form DashboardDokter
     */
    public DashboardDokter() {
        initComponents();
        setLocationRelativeTo(null);
        // Set the frame to be maximized horizontally
        setExtendedState(javax.swing.JFrame.MAXIMIZED_HORIZ);
        tampilkanJadwalPraktik();

        // Placeholder for dashboard statistics.
        // You'd replace these with actual data from a service class if available.
        LabelAngkaPasienHariIni.setText("5"); // Placeholder
        LabelAngkaResepHariIni.setText("5"); // Placeholder
        LabelAngkaRuanganTerpakai.setText("5"); // Placeholder
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JPanel(); // Renamed from jPanel1
        PanelSidebarDokter = new javax.swing.JPanel(); // Renamed from PanelSidebarAdmin2
        ButtonDashboard = new javax.swing.JButton();
        ButtonJadwalDokter = new javax.swing.JButton();
        ButtonResepPasien = new javax.swing.JButton();
        ButtonLogout = new javax.swing.JButton();
        LabelTulisanDashboard = new javax.swing.JLabel(); // Renamed from LabelDahsboardDokter
        PanelStatPasienHariIni = new javax.swing.JPanel(); // New panel for consistency
        LabelAngkaPasienHariIni = new javax.swing.JLabel();
        LabelPasienHariIni = new javax.swing.JLabel();
        PanelStatResepHariIni = new javax.swing.JPanel(); // New panel for consistency
        LabelResepHariIni = new javax.swing.JLabel();
        LabelAngkaResepHariIni = new javax.swing.JLabel();
        PanelStatRuanganTerpakai = new javax.swing.JPanel(); // New panel for consistency
        LabelRuanganTerpakai = new javax.swing.JLabel();
        LabelAngkaRuanganTerpakai = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelJadwalPraktik = new javax.swing.JTable();
        LabelJadwalPraktik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard Dokter - Sistem Informasi Klinik"); // Updated title

        PanelUtama.setBackground(new java.awt.Color(240, 240, 240)); // Light grey background
        PanelUtama.setPreferredSize(new java.awt.Dimension(1000, 700)); // Increased size for better layout

        PanelSidebarDokter.setBackground(new java.awt.Color(0, 51, 102)); // Dark blue
        PanelSidebarDokter.setPreferredSize(new java.awt.Dimension(220, 700)); // Wider sidebar

        ButtonDashboard.setBackground(new java.awt.Color(0, 102, 153)); // Slightly lighter blue for active
        ButtonDashboard.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 15)); // Bold and larger
        ButtonDashboard.setForeground(new java.awt.Color(255, 255, 255)); // White text
        ButtonDashboard.setText("Dashboard");
        ButtonDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15)); // Padding
        ButtonDashboard.setFocusPainted(false); // Remove focus border
        ButtonDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard.png"))); // Add icon
        ButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDashboardActionPerformed(evt);
            }
        });

        ButtonJadwalDokter.setBackground(new java.awt.Color(0, 51, 102));
        ButtonJadwalDokter.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonJadwalDokter.setForeground(new java.awt.Color(255, 255, 255));
        ButtonJadwalDokter.setText("Jadwal Praktik"); // Changed text for clarity
        ButtonJadwalDokter.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonJadwalDokter.setFocusPainted(false);
        ButtonJadwalDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jadwal_dokter.png"))); // Add icon
        ButtonJadwalDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonJadwalDokterActionPerformed(evt);
            }
        });

        ButtonResepPasien.setBackground(new java.awt.Color(0, 51, 102));
        ButtonResepPasien.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonResepPasien.setForeground(new java.awt.Color(255, 255, 255));
        ButtonResepPasien.setText("Resep Pasien");
        ButtonResepPasien.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonResepPasien.setFocusPainted(false);
        ButtonResepPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/resep.png"))); // Add icon
        ButtonResepPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResepPasienActionPerformed(evt);
            }
        });

        ButtonLogout.setBackground(new java.awt.Color(204, 0, 0)); // Red for logout
        ButtonLogout.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14));
        ButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogout.setText("Logout");
        ButtonLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonLogout.setFocusPainted(false);
        ButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // Add icon
        ButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSidebarDokterLayout = new javax.swing.GroupLayout(PanelSidebarDokter);
        PanelSidebarDokter.setLayout(PanelSidebarDokterLayout);
        PanelSidebarDokterLayout.setHorizontalGroup(
            PanelSidebarDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSidebarDokterLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelSidebarDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonResepPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonJadwalDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(ButtonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PanelSidebarDokterLayout.setVerticalGroup(
            PanelSidebarDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSidebarDokterLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(ButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(ButtonJadwalDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonResepPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // Pushed logout to bottom
                .addComponent(ButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        LabelTulisanDashboard.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 30)); // Larger font
        LabelTulisanDashboard.setForeground(new java.awt.Color(0, 51, 102)); // Dark blue text
        LabelTulisanDashboard.setText("Selamat Datang di Dashboard Dokter!");

        PanelStatPasienHariIni.setBackground(new java.awt.Color(235, 250, 252));
        PanelStatPasienHariIni.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 153))); // Border
        PanelStatPasienHariIni.setPreferredSize(new java.awt.Dimension(200, 100)); // Increased size

        LabelAngkaPasienHariIni.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 48)); // Larger font
        LabelAngkaPasienHariIni.setForeground(new java.awt.Color(0, 51, 102));
        LabelAngkaPasienHariIni.setText("5"); // Placeholder

        LabelPasienHariIni.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18));
        LabelPasienHariIni.setText("Pasien Hari Ini");

        javax.swing.GroupLayout PanelStatPasienHariIniLayout = new javax.swing.GroupLayout(PanelStatPasienHariIni);
        PanelStatPasienHariIni.setLayout(PanelStatPasienHariIniLayout);
        PanelStatPasienHariIniLayout.setHorizontalGroup(
            PanelStatPasienHariIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStatPasienHariIniLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(PanelStatPasienHariIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelStatPasienHariIniLayout.createSequentialGroup()
                        .addComponent(LabelAngkaPasienHariIni)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelStatPasienHariIniLayout.createSequentialGroup()
                        .addComponent(LabelPasienHariIni)
                        .addGap(41, 41, 41))))
        );
        PanelStatPasienHariIniLayout.setVerticalGroup(
            PanelStatPasienHariIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelStatPasienHariIniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelPasienHariIni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelAngkaPasienHariIni)
                .addGap(16, 16, 16))
        );

        PanelStatResepHariIni.setBackground(new java.awt.Color(235, 250, 252));
        PanelStatResepHariIni.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 153)));
        PanelStatResepHariIni.setPreferredSize(new java.awt.Dimension(200, 100));

        LabelResepHariIni.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18));
        LabelResepHariIni.setText("Resep Hari Ini");

        LabelAngkaResepHariIni.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 48));
        LabelAngkaResepHariIni.setForeground(new java.awt.Color(0, 51, 102));
        LabelAngkaResepHariIni.setText("5"); // Placeholder

        javax.swing.GroupLayout PanelStatResepHariIniLayout = new javax.swing.GroupLayout(PanelStatResepHariIni);
        PanelStatResepHariIni.setLayout(PanelStatResepHariIniLayout);
        PanelStatResepHariIniLayout.setHorizontalGroup(
            PanelStatResepHariIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStatResepHariIniLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(PanelStatResepHariIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelStatResepHariIniLayout.createSequentialGroup()
                        .addComponent(LabelResepHariIni)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelStatResepHariIniLayout.createSequentialGroup()
                        .addComponent(LabelAngkaResepHariIni)
                        .addGap(81, 81, 81))))
        );
        PanelStatResepHariIniLayout.setVerticalGroup(
            PanelStatResepHariIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelStatResepHariIniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelResepHariIni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelAngkaResepHariIni)
                .addGap(16, 16, 16))
        );

        PanelStatRuanganTerpakai.setBackground(new java.awt.Color(235, 250, 252));
        PanelStatRuanganTerpakai.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 153)));
        PanelStatRuanganTerpakai.setPreferredSize(new java.awt.Dimension(200, 100));

        LabelRuanganTerpakai.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18));
        LabelRuanganTerpakai.setText("Ruangan Terpakai");

        LabelAngkaRuanganTerpakai.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 48));
        LabelAngkaRuanganTerpakai.setForeground(new java.awt.Color(0, 51, 102));
        LabelAngkaRuanganTerpakai.setText("5"); // Placeholder

        javax.swing.GroupLayout PanelStatRuanganTerpakaiLayout = new javax.swing.GroupLayout(PanelStatRuanganTerpakai);
        PanelStatRuanganTerpakai.setLayout(PanelStatRuanganTerpakaiLayout);
        PanelStatRuanganTerpakaiLayout.setHorizontalGroup(
            PanelStatRuanganTerpakaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStatRuanganTerpakaiLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(PanelStatRuanganTerpakaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelStatRuanganTerpakaiLayout.createSequentialGroup()
                        .addComponent(LabelRuanganTerpakai)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelStatRuanganTerpakaiLayout.createSequentialGroup()
                        .addComponent(LabelAngkaRuanganTerpakai)
                        .addGap(81, 81, 81))))
        );
        PanelStatRuanganTerpakaiLayout.setVerticalGroup(
            PanelStatRuanganTerpakaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelStatRuanganTerpakaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelRuanganTerpakai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelAngkaRuanganTerpakai)
                .addGap(16, 16, 16))
        );

        TabelJadwalPraktik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Jadwal", "Hari", "Jam Mulai", "Jam Berakhir"
            }
        ));
        TabelJadwalPraktik.setRowHeight(25); // Increased row height
        TabelJadwalPraktik.getTableHeader().setFont(new Font("Franklin Gothic Medium", Font.BOLD, 12)); // Bold header
        jScrollPane1.setViewportView(TabelJadwalPraktik);

        LabelJadwalPraktik.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24));
        LabelJadwalPraktik.setForeground(new java.awt.Color(0, 51, 102));
        LabelJadwalPraktik.setText("Jadwal Praktik Anda"); // Changed text for clarity

        javax.swing.GroupLayout PanelUtamaLayout = new javax.swing.GroupLayout(PanelUtama);
        PanelUtama.setLayout(PanelUtamaLayout);
        PanelUtamaLayout.setHorizontalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addComponent(PanelSidebarDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTulisanDashboard)
                    .addGroup(PanelUtamaLayout.createSequentialGroup()
                        .addComponent(PanelStatPasienHariIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(PanelStatResepHariIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(PanelStatRuanganTerpakai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelJadwalPraktik)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)) // Adjusted size for table
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelUtamaLayout.setVerticalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSidebarDokter, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LabelTulisanDashboard)
                .addGap(40, 40, 40)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelStatPasienHariIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelStatResepHariIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelStatRuanganTerpakai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(LabelJadwalPraktik)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, Short.MAX_VALUE) // Adjusted height
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE) // Adjusted preferred size
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE) // Adjusted preferred size
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDashboardActionPerformed
        this.dispose();
        DashboardDokter dashboard = new DashboardDokter();
        dashboard.setVisible(true);
    }//GEN-LAST:event_ButtonDashboardActionPerformed

    private void ButtonJadwalDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonJadwalDokterActionPerformed
        this.dispose();
        JadwalDokterDokter jadwalDokter = new JadwalDokterDokter();
        jadwalDokter.setVisible(true);
    }//GEN-LAST:event_ButtonJadwalDokterActionPerformed

    private void ButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogoutActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin logout?",
                "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION);

        if (pilihan == JOptionPane.YES_OPTION) {
            this.dispose();
            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_ButtonLogoutActionPerformed

    private void ButtonResepPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResepPasienActionPerformed
        this.dispose();
        ResepPasienDokter resepPasien = new ResepPasienDokter();
        resepPasien.setVisible(true);
    }//GEN-LAST:event_ButtonResepPasienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardDokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDashboard;
    private javax.swing.JButton ButtonJadwalDokter;
    private javax.swing.JButton ButtonLogout;
    private javax.swing.JButton ButtonResepPasien;
    private javax.swing.JLabel LabelAngkaPasienHariIni;
    private javax.swing.JLabel LabelAngkaResepHariIni;
    private javax.swing.JLabel LabelAngkaRuanganTerpakai;
    private javax.swing.JLabel LabelJadwalPraktik;
    private javax.swing.JLabel LabelPasienHariIni;
    private javax.swing.JLabel LabelResepHariIni;
    private javax.swing.JLabel LabelRuanganTerpakai;
    private javax.swing.JLabel LabelTulisanDashboard;
    private javax.swing.JPanel PanelStatPasienHariIni;
    private javax.swing.JPanel PanelStatResepHariIni;
    private javax.swing.JPanel PanelStatRuanganTerpakai;
    private javax.swing.JPanel PanelSidebarDokter;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JTable TabelJadwalPraktik;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}