/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klinik_pbo;

import dao.JadwalDokterDAO;
import javax.swing.table.DefaultTableModel;
import java.awt.Color; // Added for color
import java.awt.Font;  // Added for font
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.JadwalDokter;

/**
 *
 * @author avvjelly
 */
public class JadwalDokterDokter extends javax.swing.JFrame {

    public void tampilkanDataJadwalDokter() {
        // Pastikan dijalankan di Event Dispatch Thread (EDT)
        SwingUtilities.invokeLater(() -> {
            try {
                // Ambil data dari DAO
                // Note: If you want to filter by the logged-in doctor, you'll need to pass doctor ID here
                List<JadwalDokter> daftar = JadwalDokterDAO.getAllJadwalDokterLengkap();

                // Bersihkan tabel
                DefaultTableModel model = (DefaultTableModel) TabelJadwalDokter.getModel();
                model.setRowCount(0);

                // Jika data kosong, tampilkan pesan (opsional, karena tabel mungkin kosong di awal)
                // if (daftar.isEmpty()) {
                //     JOptionPane.showMessageDialog(this, "Tidak ada data jadwal dokter.", "Info", JOptionPane.INFORMATION_MESSAGE);
                //     return;
                // }

                // Isi tabel
                for (JadwalDokter jd : daftar) {
                    model.addRow(new Object[]{
                        jd.getIdJadwalDokter(),
                        jd.getNamaDokter(),
                        jd.getHari(),
                        jd.getNamaRuangan()
                    });
                }

                // Paksa update UI
                TabelJadwalDokter.revalidate();
                TabelJadwalDokter.repaint();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        });
    }

    /**
     * Creates new form JadwalDokterDokter
     */
    public JadwalDokterDokter() {
        initComponents();
        setLocationRelativeTo(null);
        // Set the frame to be maximized horizontally
        setExtendedState(javax.swing.JFrame.MAXIMIZED_HORIZ);
        tampilkanDataJadwalDokter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JPanel(); // Renamed from jPanel1
        PanelSidebarDokter = new javax.swing.JPanel(); // Renamed from PanelSidebarAdmin2
        ButtonDashboard = new javax.swing.JButton();
        ButtonJadwalDokter = new javax.swing.JButton();
        ButtonResepPasien = new javax.swing.JButton();
        ButtonLogout = new javax.swing.JButton();
        LabelJudulHalaman = new javax.swing.JLabel(); // Renamed from LabelJadwalDokter
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelJadwalDokter = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jadwal Praktik Dokter - Sistem Informasi Klinik"); // Updated title

        PanelUtama.setBackground(new java.awt.Color(240, 240, 240)); // Light grey background
        PanelUtama.setPreferredSize(new java.awt.Dimension(1000, 700)); // Increased size for better layout

        PanelSidebarDokter.setBackground(new java.awt.Color(0, 51, 102)); // Dark blue
        PanelSidebarDokter.setPreferredSize(new java.awt.Dimension(220, 700)); // Wider sidebar

        ButtonDashboard.setBackground(new java.awt.Color(0, 51, 102)); // Default sidebar button color
        ButtonDashboard.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // Normal font
        ButtonDashboard.setForeground(new java.awt.Color(255, 255, 255)); // White text
        ButtonDashboard.setText("Dashboard");
        ButtonDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15)); // Padding
        ButtonDashboard.setFocusPainted(false); // Remove focus border
        ButtonDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard.png"))); // Add icon
        ButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDashboardActionPerformed(evt);
            }
        });

        ButtonJadwalDokter.setBackground(new java.awt.Color(0, 102, 153)); // Highlight for current page
        ButtonJadwalDokter.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 15)); // Bold and larger
        ButtonJadwalDokter.setForeground(new java.awt.Color(255, 255, 255));
        ButtonJadwalDokter.setText("Jadwal Praktik"); // Consistent text
        ButtonJadwalDokter.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonJadwalDokter.setFocusPainted(false);
        ButtonJadwalDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jadwal_dokter.png"))); // Add icon
        // No action listener needed as it's the current page

        ButtonResepPasien.setBackground(new java.awt.Color(0, 51, 102));
        ButtonResepPasien.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonResepPasien.setForeground(new java.awt.Color(255, 255, 255));
        ButtonResepPasien.setText("Resep Pasien");
        ButtonResepPasien.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonResepPasien.setFocusPainted(false);
        ButtonResepPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/resep.png"))); // Add icon
        ButtonResepPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResepPasienActionPerformed(evt);
            }
        });

        ButtonLogout.setBackground(new java.awt.Color(204, 0, 0)); // Red for logout
        ButtonLogout.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14));
        ButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogout.setText("Logout");
        ButtonLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonLogout.setFocusPainted(false);
        ButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // Add icon
        ButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSidebarDokterLayout = new javax.swing.GroupLayout(PanelSidebarDokter);
        PanelSidebarDokter.setLayout(PanelSidebarDokterLayout);
        PanelSidebarDokterLayout.setHorizontalGroup(
            PanelSidebarDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSidebarDokterLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelSidebarDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonResepPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonJadwalDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(ButtonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PanelSidebarDokterLayout.setVerticalGroup(
            PanelSidebarDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSidebarDokterLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(ButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(ButtonJadwalDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonResepPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // Pushed logout to bottom
                .addComponent(ButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        LabelJudulHalaman.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 30)); // Larger font
        LabelJudulHalaman.setForeground(new java.awt.Color(0, 51, 102)); // Dark blue text
        LabelJudulHalaman.setText("Jadwal Praktik Dokter"); // Specific title for this page

        TabelJadwalDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Jadwal", "Nama Dokter", "Hari", "Ruangan" // Updated column names
            }
        ));
        TabelJadwalDokter.setRowHeight(25); // Increased row height
        TabelJadwalDokter.getTableHeader().setFont(new Font("Franklin Gothic Medium", Font.BOLD, 12)); // Bold header
        jScrollPane1.setViewportView(TabelJadwalDokter);

        javax.swing.GroupLayout PanelUtamaLayout = new javax.swing.GroupLayout(PanelUtama);
        PanelUtama.setLayout(PanelUtamaLayout);
        PanelUtamaLayout.setHorizontalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addComponent(PanelSidebarDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelJudulHalaman)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)) // Adjusted size for table
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelUtamaLayout.setVerticalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSidebarDokter, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LabelJudulHalaman)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, Short.MAX_VALUE) // Adjusted height
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE) // Adjusted preferred size
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE) // Adjusted preferred size
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDashboardActionPerformed
        this.dispose();
        DashboardDokter dashboard = new DashboardDokter();
        dashboard.setVisible(true);
    }//GEN-LAST:event_ButtonDashboardActionPerformed

    private void ButtonJadwalDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonJadwalDokterActionPerformed
        // This is the current page, so no action needed, or refresh if desired.
        // If you intended to have another form for managing schedules, create that form and redirect here.
    }//GEN-LAST:event_ButtonJadwalDokterActionPerformed

    private void ButtonResepPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResepPasienActionPerformed
        this.dispose();
        ResepPasienDokter resepPasien = new ResepPasienDokter();
        resepPasien.setVisible(true);
    }//GEN-LAST:event_ButtonResepPasienActionPerformed

    private void ButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogoutActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin logout?",
                "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION);

        if (pilihan == JOptionPane.YES_OPTION) {
            this.dispose();
            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_ButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JadwalDokterDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JadwalDokterDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JadwalDokterDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JadwalDokterDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JadwalDokterDokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDashboard;
    private javax.swing.JButton ButtonJadwalDokter;
    private javax.swing.JButton ButtonLogout;
    private javax.swing.JButton ButtonResepPasien;
    private javax.swing.JLabel LabelJudulHalaman;
    private javax.swing.JPanel PanelSidebarDokter;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JTable TabelJadwalDokter;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}