/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klinik_pbo;

import controller.PasienController;
import dao.PasienDAO; // Ensure this is correctly imported
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Pasien; // Ensure this is correctly imported
import klinik_pbo.koneksi; // Ensure this is correctly imported

/**
 *
 * @author avvjelly
 */
public class PendaftaranPasienAdmin extends javax.swing.JFrame {

    /**
     * Creates new form PendaftaranPasienAdmin
     */
    public PendaftaranPasienAdmin() {
        initComponents();
        setLocationRelativeTo(null); // Center the frame on screen
        // Set the frame to be maximized horizontally like DashboardAdmin
        setExtendedState(javax.swing.JFrame.MAXIMIZED_HORIZ);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JPanel(); // Renamed from jPanel1
        PanelSidebarAdmin = new javax.swing.JPanel(); // Renamed from PanelSidebarAdmin2
        ButtonDashboard = new javax.swing.JButton();
        ButtonDaftarPasien = new javax.swing.JButton();
        ButtonDaftarDokter = new javax.swing.JButton();
        ButtonDaftarObat = new javax.swing.JButton();
        ButtonDaftarRuangan = new javax.swing.JButton();
        ButtonPendaftaranPasien = new javax.swing.JButton();
        ButtonPendaftaranDokter = new javax.swing.JButton();
        ButtonPendaftaranObat = new javax.swing.JButton();
        ButtonJadwalDokter = new javax.swing.JButton();
        ButtonResepPasien = new javax.swing.JButton();
        ButtonLogout = new javax.swing.JButton();
        LabelJudulHalaman = new javax.swing.JLabel(); // New label for page title
        LabelMasukkanID = new javax.swing.JLabel();
        TextfieldID = new javax.swing.JTextField();
        LabelMasukkanNama = new javax.swing.JLabel();
        TextfieldNama = new javax.swing.JTextField();
        LabelMasukkanAlamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextareaAlamat = new javax.swing.JTextArea();
        LabelMasukkanTelepon = new javax.swing.JLabel(); // Renamed from LabelMasukkanAlamat1
        TextfieldTelepon = new javax.swing.JTextField();
        ButtonSendPasien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pendaftaran Pasien - Sistem Informasi Klinik"); // Updated title

        PanelUtama.setBackground(new java.awt.Color(240, 240, 240)); // Light grey background
        PanelUtama.setPreferredSize(new java.awt.Dimension(1000, 700)); // Increased size for better layout

        PanelSidebarAdmin.setBackground(new java.awt.Color(0, 51, 102)); // Dark blue
        PanelSidebarAdmin.setPreferredSize(new java.awt.Dimension(220, 700)); // Wider sidebar

        ButtonDashboard.setBackground(new java.awt.Color(0, 51, 102)); // Default sidebar button color
        ButtonDashboard.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // Normal font
        ButtonDashboard.setForeground(new java.awt.Color(255, 255, 255)); // White text
        ButtonDashboard.setText("Dashboard");
        ButtonDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15)); // Padding
        ButtonDashboard.setFocusPainted(false); // Remove focus border
        ButtonDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard.png")));
        ButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDashboardActionPerformed(evt);
            }
        });

        ButtonDaftarPasien.setBackground(new java.awt.Color(0, 51, 102));
        ButtonDaftarPasien.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonDaftarPasien.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDaftarPasien.setText("Daftar Pasien");
        ButtonDaftarPasien.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonDaftarPasien.setFocusPainted(false);
        ButtonDaftarPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/daftar_pasien.png")));
        ButtonDaftarPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarPasienActionPerformed(evt);
            }
        });

        ButtonDaftarDokter.setBackground(new java.awt.Color(0, 51, 102));
        ButtonDaftarDokter.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonDaftarDokter.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDaftarDokter.setText("Daftar Dokter");
        ButtonDaftarDokter.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonDaftarDokter.setFocusPainted(false);
        ButtonDaftarDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/daftar_dokter.png")));
        ButtonDaftarDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarDokterActionPerformed(evt);
            }
        });

        ButtonDaftarObat.setBackground(new java.awt.Color(0, 51, 102));
        ButtonDaftarObat.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonDaftarObat.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDaftarObat.setText("Daftar Obat");
        ButtonDaftarObat.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonDaftarObat.setFocusPainted(false);
        ButtonDaftarObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/daftar_obat.png")));
        ButtonDaftarObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarObatActionPerformed(evt);
            }
        });

        ButtonDaftarRuangan.setBackground(new java.awt.Color(0, 51, 102));
        ButtonDaftarRuangan.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonDaftarRuangan.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDaftarRuangan.setText("Daftar Ruangan");
        ButtonDaftarRuangan.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonDaftarRuangan.setFocusPainted(false);
        ButtonDaftarRuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ruangan.png")));
        ButtonDaftarRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarRuanganActionPerformed(evt);
            }
        });

        ButtonPendaftaranPasien.setBackground(new java.awt.Color(0, 102, 153)); // Highlight for current page
        ButtonPendaftaranPasien.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 15)); // Bold and larger
        ButtonPendaftaranPasien.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPendaftaranPasien.setText("Pendaftaran Pasien");
        ButtonPendaftaranPasien.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonPendaftaranPasien.setFocusPainted(false);
        ButtonPendaftaranPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pendaftaran_pasien.png")));
        // No action listener needed as it's the current page

        ButtonPendaftaranDokter.setBackground(new java.awt.Color(0, 51, 102));
        ButtonPendaftaranDokter.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonPendaftaranDokter.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPendaftaranDokter.setText("Pendaftaran Dokter");
        ButtonPendaftaranDokter.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonPendaftaranDokter.setFocusPainted(false);
        ButtonPendaftaranDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pendaftaran_dokter.png")));
        ButtonPendaftaranDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPendaftaranDokterActionPerformed(evt);
            }
        });

        ButtonPendaftaranObat.setBackground(new java.awt.Color(0, 51, 102));
        ButtonPendaftaranObat.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonPendaftaranObat.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPendaftaranObat.setText("Pendaftaran Obat");
        ButtonPendaftaranObat.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonPendaftaranObat.setFocusPainted(false);
        ButtonPendaftaranObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pendaftaran_obat.png")));
        ButtonPendaftaranObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPendaftaranObatActionPerformed(evt);
            }
        });

        ButtonJadwalDokter.setBackground(new java.awt.Color(0, 51, 102));
        ButtonJadwalDokter.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonJadwalDokter.setForeground(new java.awt.Color(255, 255, 255));
        ButtonJadwalDokter.setText("Jadwal Dokter");
        ButtonJadwalDokter.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonJadwalDokter.setFocusPainted(false);
        ButtonJadwalDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jadwal_dokter.png")));
        ButtonJadwalDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonJadwalDokterActionPerformed(evt);
            }
        });

        ButtonResepPasien.setBackground(new java.awt.Color(0, 51, 102));
        ButtonResepPasien.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        ButtonResepPasien.setForeground(new java.awt.Color(255, 255, 255));
        ButtonResepPasien.setText("Resep Pasien");
        ButtonResepPasien.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonResepPasien.setFocusPainted(false);
        ButtonResepPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/resep.png")));
        ButtonResepPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResepPasienActionPerformed(evt);
            }
        });

        ButtonLogout.setBackground(new java.awt.Color(204, 0, 0)); // Red for logout
        ButtonLogout.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14));
        ButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogout.setText("Logout");
        ButtonLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        ButtonLogout.setFocusPainted(false);
        ButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png")));
        ButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSidebarAdminLayout = new javax.swing.GroupLayout(PanelSidebarAdmin);
        PanelSidebarAdmin.setLayout(PanelSidebarAdminLayout);
        PanelSidebarAdminLayout.setHorizontalGroup(
            PanelSidebarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSidebarAdminLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PanelSidebarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonResepPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonJadwalDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPendaftaranObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPendaftaranDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPendaftaranPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonDaftarRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonDaftarObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonDaftarDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonDaftarPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(ButtonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PanelSidebarAdminLayout.setVerticalGroup(
            PanelSidebarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSidebarAdminLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(ButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(ButtonDaftarPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarObat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(ButtonPendaftaranPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPendaftaranDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPendaftaranObat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonJadwalDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonResepPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE) // Pushed logout to bottom
                .addComponent(ButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        LabelJudulHalaman.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 30)); // Larger font
        LabelJudulHalaman.setForeground(new java.awt.Color(0, 51, 102)); // Dark blue text
        LabelJudulHalaman.setText("Form Pendaftaran Pasien"); // Specific title for this page

        LabelMasukkanID.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        LabelMasukkanID.setText("ID Pasien :");
        LabelMasukkanID.setForeground(new java.awt.Color(0, 51, 102));

        TextfieldID.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // Consistent font
        TextfieldID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))); // Subtle border
        TextfieldID.setPreferredSize(new java.awt.Dimension(6, 30)); // Consistent height
        TextfieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfieldIDActionPerformed(evt);
            }
        });

        LabelMasukkanNama.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        LabelMasukkanNama.setText("Nama Pasien :");
        LabelMasukkanNama.setForeground(new java.awt.Color(0, 51, 102));

        TextfieldNama.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14));
        TextfieldNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        TextfieldNama.setPreferredSize(new java.awt.Dimension(6, 30));
        TextfieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfieldNamaActionPerformed(evt);
            }
        });

        LabelMasukkanAlamat.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14));
        LabelMasukkanAlamat.setText("Alamat Pasien :");
        LabelMasukkanAlamat.setForeground(new java.awt.Color(0, 51, 102));

        TextareaAlamat.setColumns(20);
        TextareaAlamat.setRows(5);
        TextareaAlamat.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14));
        TextareaAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jScrollPane1.setViewportView(TextareaAlamat);

        LabelMasukkanTelepon.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // Renamed
        LabelMasukkanTelepon.setText("Telepon Pasien :");
        LabelMasukkanTelepon.setForeground(new java.awt.Color(0, 51, 102));

        TextfieldTelepon.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14));
        TextfieldTelepon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        TextfieldTelepon.setPreferredSize(new java.awt.Dimension(6, 30));
        TextfieldTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfieldTeleponActionPerformed(evt);
            }
        });

        ButtonSendPasien.setBackground(new java.awt.Color(0, 153, 51)); // Green for Send/Submit
        ButtonSendPasien.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // Bold font
        ButtonSendPasien.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSendPasien.setText("Daftarkan Pasien"); // More descriptive text
        ButtonSendPasien.setPreferredSize(new java.awt.Dimension(150, 40)); // Larger button
        ButtonSendPasien.setFocusPainted(false);
        ButtonSendPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSendPasienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelUtamaLayout = new javax.swing.GroupLayout(PanelUtama);
        PanelUtama.setLayout(PanelUtamaLayout);
        PanelUtamaLayout.setHorizontalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addComponent(PanelSidebarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelJudulHalaman)
                    .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ButtonSendPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelMasukkanID)
                            .addComponent(TextfieldID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelMasukkanNama)
                            .addComponent(TextfieldNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelMasukkanAlamat)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE) // Adjust width of textarea
                            .addComponent(LabelMasukkanTelepon)
                            .addComponent(TextfieldTelepon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelUtamaLayout.setVerticalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSidebarAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LabelJudulHalaman)
                .addGap(40, 40, 40)
                .addComponent(LabelMasukkanID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextfieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelMasukkanNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextfieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelMasukkanAlamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelMasukkanTelepon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextfieldTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ButtonSendPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE) // Adjusted preferred size
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE) // Adjusted preferred size
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDashboardActionPerformed
        this.dispose();
        DashboardAdmin dashboard = new DashboardAdmin();
        dashboard.setVisible(true);
    }//GEN-LAST:event_ButtonDashboardActionPerformed

    private void ButtonDaftarPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarPasienActionPerformed
        this.dispose();
        DaftarPasienAdmin daftarpasien = new DaftarPasienAdmin();
        daftarpasien.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarPasienActionPerformed

    private void ButtonDaftarDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarDokterActionPerformed
        this.dispose();
        DaftarDokterAdmin daftardokter = new DaftarDokterAdmin();
        daftardokter.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarDokterActionPerformed

    private void ButtonDaftarObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarObatActionPerformed
        this.dispose();
        DaftarObatAdmin daftarobat = new DaftarObatAdmin();
        daftarobat.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarObatActionPerformed

    private void TextfieldTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfieldTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextfieldTeleponActionPerformed

    private void ButtonDaftarRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarRuanganActionPerformed
        this.dispose();
        DaftarRuanganAdmin daftarruangan = new DaftarRuanganAdmin();
        daftarruangan.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarRuanganActionPerformed

    private void ButtonSendPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSendPasienActionPerformed
        try {
            String id = TextfieldID.getText().trim();
            String nama = TextfieldNama.getText().trim();
            String alamat = TextareaAlamat.getText().trim();
            String telepon = TextfieldTelepon.getText().trim();

            // Input Validation
            if (id.isEmpty() || nama.isEmpty() || alamat.isEmpty() || telepon.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua field harus diisi terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            PasienController pc = new PasienController();
            pc.tambahPasien(id, nama, alamat, telepon);

            JOptionPane.showMessageDialog(this, "Data pasien berhasil disimpan!");

            // Reset form
            TextfieldID.setText("");
            TextfieldNama.setText("");
            TextareaAlamat.setText("");
            TextfieldTelepon.setText("");

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data pasien.\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonSendPasienActionPerformed

    private void TextfieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextfieldIDActionPerformed

    private void ButtonPendaftaranDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPendaftaranDokterActionPerformed
        this.dispose();
        PendaftaranDokterAdmin daftardokter = new PendaftaranDokterAdmin();
        daftardokter.setVisible(true);
    }//GEN-LAST:event_ButtonPendaftaranDokterActionPerformed

    private void ButtonPendaftaranObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPendaftaranObatActionPerformed
        this.dispose();
        PendaftaranObatAdmin daftarobat = new PendaftaranObatAdmin();
        daftarobat.setVisible(true);
    }//GEN-LAST:event_ButtonPendaftaranObatActionPerformed

    private void ButtonJadwalDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonJadwalDokterActionPerformed
        this.dispose();
        JadwalDokterAdmin daftarjadwal = new JadwalDokterAdmin();
        daftarjadwal.setVisible(true);
    }//GEN-LAST:event_ButtonJadwalDokterActionPerformed

    private void ButtonResepPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResepPasienActionPerformed
        this.dispose();
        ResepPasienAdmin daftarresep = new ResepPasienAdmin();
        daftarresep.setVisible(true);
    }//GEN-LAST:event_ButtonResepPasienActionPerformed

    private void ButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogoutActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin logout?",
                "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION);

        if (pilihan == JOptionPane.YES_OPTION) {
            this.dispose();
            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_ButtonLogoutActionPerformed

    private void TextfieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextfieldNamaActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendaftaranPasienAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendaftaranPasienAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendaftaranPasienAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendaftaranPasienAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendaftaranPasienAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDaftarDokter;
    private javax.swing.JButton ButtonDaftarObat;
    private javax.swing.JButton ButtonDaftarPasien;
    private javax.swing.JButton ButtonDaftarRuangan;
    private javax.swing.JButton ButtonDashboard;
    private javax.swing.JButton ButtonJadwalDokter;
    private javax.swing.JButton ButtonLogout;
    private javax.swing.JButton ButtonPendaftaranDokter;
    private javax.swing.JButton ButtonPendaftaranObat;
    private javax.swing.JButton ButtonPendaftaranPasien;
    private javax.swing.JButton ButtonResepPasien;
    private javax.swing.JButton ButtonSendPasien;
    private javax.swing.JLabel LabelJudulHalaman;
    private javax.swing.JLabel LabelMasukkanAlamat;
    private javax.swing.JLabel LabelMasukkanID;
    private javax.swing.JLabel LabelMasukkanNama;
    private javax.swing.JLabel LabelMasukkanTelepon;
    private javax.swing.JPanel PanelSidebarAdmin;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea TextareaAlamat;
    private javax.swing.JTextField TextfieldID;
    private javax.swing.JTextField TextfieldNama;
    private javax.swing.JTextField TextfieldTelepon;
    // End of variables declaration//GEN-END:variables
}