/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klinik_pbo;

import controller.ObatController;
import javax.swing.JOptionPane;

/**
 *
 * @author avvjelly
 */
public class PendaftaranObatAdmin extends javax.swing.JFrame {

    /**
     * Creates new form PendaftaranObatAdmin
     */
    public PendaftaranObatAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelSidebarAdmin2 = new javax.swing.JPanel();
        ButtonDashboard = new javax.swing.JButton();
        ButtonDaftarPasien = new javax.swing.JButton();
        ButtonDaftarDokter = new javax.swing.JButton();
        ButtonDaftarObat = new javax.swing.JButton();
        ButtonDaftarRuangan = new javax.swing.JButton();
        ButtonPendaftaranPasien = new javax.swing.JButton();
        ButtonPendaftaranDokter = new javax.swing.JButton();
        ButtonPendaftaranObat = new javax.swing.JButton();
        ButtonJadwalDokter = new javax.swing.JButton();
        ButtonResepPasien = new javax.swing.JButton();
        ButtonLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TextfieldID = new javax.swing.JTextField();
        TextfieldNamaObat = new javax.swing.JTextField();
        TextfieldStokObat = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        LabelID = new javax.swing.JLabel();
        LabelNamaObat = new javax.swing.JLabel();
        LabelStokObat = new javax.swing.JLabel();
        LabelHargaObat = new javax.swing.JLabel();
        TextfieldHargaObat = new javax.swing.JTextField();
        ButtonSendObat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        PanelSidebarAdmin2.setBackground(new java.awt.Color(0, 51, 102));
        PanelSidebarAdmin2.setPreferredSize(new java.awt.Dimension(200, 500));

        ButtonDashboard.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonDashboard.setText("Dashboard");
        ButtonDashboard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDashboardActionPerformed(evt);
            }
        });

        ButtonDaftarPasien.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonDaftarPasien.setText("Daftar Pasien");
        ButtonDaftarPasien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDaftarPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarPasienActionPerformed(evt);
            }
        });

        ButtonDaftarDokter.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonDaftarDokter.setText("Daftar Dokter");
        ButtonDaftarDokter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDaftarDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarDokterActionPerformed(evt);
            }
        });

        ButtonDaftarObat.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonDaftarObat.setText("Daftar Obat");
        ButtonDaftarObat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDaftarObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarObatActionPerformed(evt);
            }
        });

        ButtonDaftarRuangan.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonDaftarRuangan.setText("Daftar Ruangan");
        ButtonDaftarRuangan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDaftarRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarRuanganActionPerformed(evt);
            }
        });

        ButtonPendaftaranPasien.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonPendaftaranPasien.setText("Pendaftaran Pasien");
        ButtonPendaftaranPasien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonPendaftaranPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPendaftaranPasienActionPerformed(evt);
            }
        });

        ButtonPendaftaranDokter.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonPendaftaranDokter.setText("Pendaftaran Dokter");
        ButtonPendaftaranDokter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonPendaftaranDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPendaftaranDokterActionPerformed(evt);
            }
        });

        ButtonPendaftaranObat.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonPendaftaranObat.setText("Pendaftaran Obat");
        ButtonPendaftaranObat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ButtonJadwalDokter.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonJadwalDokter.setText("Jadwal Dokter");
        ButtonJadwalDokter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonJadwalDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonJadwalDokterActionPerformed(evt);
            }
        });

        ButtonResepPasien.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonResepPasien.setText("Resep Pasien");
        ButtonResepPasien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonResepPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResepPasienActionPerformed(evt);
            }
        });

        ButtonLogout.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonLogout.setText("Logout");
        ButtonLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSidebarAdmin2Layout = new javax.swing.GroupLayout(PanelSidebarAdmin2);
        PanelSidebarAdmin2.setLayout(PanelSidebarAdmin2Layout);
        PanelSidebarAdmin2Layout.setHorizontalGroup(
            PanelSidebarAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSidebarAdmin2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelSidebarAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonDaftarPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDaftarDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDaftarObat, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDaftarRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPendaftaranPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPendaftaranDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPendaftaranObat, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonJadwalDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonResepPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PanelSidebarAdmin2Layout.setVerticalGroup(
            PanelSidebarAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSidebarAdmin2Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(ButtonDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarPasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarDokter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarObat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarRuangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPendaftaranPasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPendaftaranDokter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPendaftaranObat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonJadwalDokter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonResepPasien)
                .addGap(34, 34, 34)
                .addComponent(ButtonLogout)
                .addContainerGap(1833, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabel1.setText("Pendaftaran Obat");

        TextfieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfieldIDActionPerformed(evt);
            }
        });

        jTextField4.setText("jTextField1");

        LabelID.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        LabelID.setText("Masukkan ID Obat:");

        LabelNamaObat.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        LabelNamaObat.setText("Masukkan Nama Obat:");

        LabelStokObat.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        LabelStokObat.setText("Masukkan Stok Obat:");

        LabelHargaObat.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        LabelHargaObat.setText("Masukkan Harga Obat:");

        ButtonSendObat.setBackground(new java.awt.Color(0, 51, 153));
        ButtonSendObat.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        ButtonSendObat.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSendObat.setText("Send");
        ButtonSendObat.setPreferredSize(new java.awt.Dimension(100, 35));
        ButtonSendObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSendObatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PanelSidebarAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4)
                            .addComponent(TextfieldID)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelNamaObat)
                                    .addComponent(LabelID)
                                    .addComponent(LabelStokObat)
                                    .addComponent(LabelHargaObat))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(TextfieldNamaObat)
                            .addComponent(TextfieldStokObat)
                            .addComponent(TextfieldHargaObat))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 211, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(182, 182, 182))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonSendObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(255, 255, 255))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PanelSidebarAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 2327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(LabelID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextfieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelNamaObat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextfieldNamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelStokObat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextfieldStokObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelHargaObat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextfieldHargaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(ButtonSendObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDashboardActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini (DaftarPasienAdmin)
        this.dispose();

        // 2. Buka form DashboardAdmin
        DashboardAdmin dashboard = new DashboardAdmin();
        dashboard.setVisible(true);
    }//GEN-LAST:event_ButtonDashboardActionPerformed

    private void ButtonDaftarPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarPasienActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini (DaftarPasienAdmin)
        this.dispose();

        // 2. Buka form DaftarPasien
        DaftarPasienAdmin daftarpasien = new DaftarPasienAdmin();
        daftarpasien.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarPasienActionPerformed

    private void ButtonDaftarDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarDokterActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini (DaftarPasienAdmin)
        this.dispose();

        // 2. Buka form DaftarPasien
        DaftarDokterAdmin daftardokter = new DaftarDokterAdmin();
        daftardokter.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarDokterActionPerformed

    private void ButtonDaftarObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarObatActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        DaftarObatAdmin daftarobat = new DaftarObatAdmin();
        daftarobat.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarObatActionPerformed

    private void ButtonDaftarRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarRuanganActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        DaftarRuanganAdmin daftarruangan = new DaftarRuanganAdmin();
        daftarruangan.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarRuanganActionPerformed

    private void TextfieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextfieldIDActionPerformed

    private void ButtonPendaftaranDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPendaftaranDokterActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        PendaftaranDokterAdmin daftardokter = new PendaftaranDokterAdmin();
        daftardokter.setVisible(true);
    }//GEN-LAST:event_ButtonPendaftaranDokterActionPerformed

    private void ButtonPendaftaranPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPendaftaranPasienActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        PendaftaranPasienAdmin daftarpasien = new PendaftaranPasienAdmin();
        daftarpasien.setVisible(true);
    }//GEN-LAST:event_ButtonPendaftaranPasienActionPerformed

    private void ButtonJadwalDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonJadwalDokterActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        JadwalDokterAdmin daftarjadwal = new JadwalDokterAdmin();
        daftarjadwal.setVisible(true);
    }//GEN-LAST:event_ButtonJadwalDokterActionPerformed

    private void ButtonResepPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResepPasienActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        ResepPasienAdmin daftarresep = new ResepPasienAdmin();
        daftarresep.setVisible(true);
    }//GEN-LAST:event_ButtonResepPasienActionPerformed

    private void ButtonSendObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSendObatActionPerformed
        // TODO add your handling code here:
                try {
    String id = TextfieldID.getText().trim();
    String nama = TextfieldNamaObat.getText().trim();
    String stokText = TextfieldStokObat.getText().trim();
    String hargaText = TextfieldHargaObat.getText().trim();

    // Validasi input
    if (id.isEmpty() || nama.isEmpty() || stokText.isEmpty() || hargaText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int stok = Integer.parseInt(stokText);
    double harga = Double.parseDouble(hargaText);

    ObatController oc = new ObatController();
    oc.tambahObat(id, nama, stok, harga);

    JOptionPane.showMessageDialog(this, "Data obat berhasil disimpan!");

    // Reset form
    TextfieldID.setText("");
    TextfieldNamaObat.setText("");
    TextfieldStokObat.setText("");
    TextfieldHargaObat.setText("");

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Gagal menyimpan data obat.\n" + e.getMessage());
}

    }//GEN-LAST:event_ButtonSendObatActionPerformed

    private void ButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogoutActionPerformed
        // TODO add your handling code here:
        // Tampilkan dialog konfirmasi
    int pilihan = JOptionPane.showConfirmDialog(this, 
                    "Apakah Anda yakin ingin logout?", 
                    "Konfirmasi Logout", 
                    JOptionPane.YES_NO_OPTION);

    // Jika pengguna memilih "Yes"
    if (pilihan == JOptionPane.YES_OPTION) {
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form login
        Login login = new Login();
        login.setVisible(true);
      }
    }//GEN-LAST:event_ButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendaftaranObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendaftaranObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendaftaranObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendaftaranObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendaftaranObatAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDaftarDokter;
    private javax.swing.JButton ButtonDaftarObat;
    private javax.swing.JButton ButtonDaftarPasien;
    private javax.swing.JButton ButtonDaftarRuangan;
    private javax.swing.JButton ButtonDashboard;
    private javax.swing.JButton ButtonJadwalDokter;
    private javax.swing.JButton ButtonLogout;
    private javax.swing.JButton ButtonPendaftaranDokter;
    private javax.swing.JButton ButtonPendaftaranObat;
    private javax.swing.JButton ButtonPendaftaranPasien;
    private javax.swing.JButton ButtonResepPasien;
    private javax.swing.JButton ButtonSendObat;
    private javax.swing.JLabel LabelHargaObat;
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelNamaObat;
    private javax.swing.JLabel LabelStokObat;
    private javax.swing.JPanel PanelSidebarAdmin2;
    private javax.swing.JTextField TextfieldHargaObat;
    private javax.swing.JTextField TextfieldID;
    private javax.swing.JTextField TextfieldNamaObat;
    private javax.swing.JTextField TextfieldStokObat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
