/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klinik_pbo;

import controller.PasienController;
import dao.PasienDAO;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Pasien;
import klinik_pbo.koneksi;

/**
 *
 * @author avvjelly
 */
public class PendaftaranPasienAdmin extends javax.swing.JFrame {

    /**
     * Creates new form PendaftaranPasienAdmin
     */
    public PendaftaranPasienAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelSidebarAdmin2 = new javax.swing.JPanel();
        ButtonDashboard = new javax.swing.JButton();
        ButtonDaftarPasien = new javax.swing.JButton();
        ButtonDaftarDokter = new javax.swing.JButton();
        ButtonDaftarObat = new javax.swing.JButton();
        ButtonDaftarRuangan = new javax.swing.JButton();
        ButtonPendaftaranPasien = new javax.swing.JButton();
        ButtonPendaftaranDokter = new javax.swing.JButton();
        ButtonPendaftaranObat = new javax.swing.JButton();
        ButtonJadwalDokter = new javax.swing.JButton();
        ButtonResepPasien = new javax.swing.JButton();
        ButtonLogout = new javax.swing.JButton();
        LabelPendaftaranPasien = new javax.swing.JLabel();
        TextfieldNama = new javax.swing.JTextField();
        LabelMasukkanNama = new javax.swing.JLabel();
        LabelMasukkanAlamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextareaAlamat = new javax.swing.JTextArea();
        LabelMasukkanAlamat1 = new javax.swing.JLabel();
        TextfieldTelepon = new javax.swing.JTextField();
        ButtonSendPasien = new javax.swing.JButton();
        LabelMasukkanID = new javax.swing.JLabel();
        TextfieldID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        PanelSidebarAdmin2.setBackground(new java.awt.Color(0, 51, 102));
        PanelSidebarAdmin2.setPreferredSize(new java.awt.Dimension(200, 500));

        ButtonDashboard.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonDashboard.setText("Dashboard");
        ButtonDashboard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDashboardActionPerformed(evt);
            }
        });

        ButtonDaftarPasien.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonDaftarPasien.setText("Daftar Pasien");
        ButtonDaftarPasien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDaftarPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarPasienActionPerformed(evt);
            }
        });

        ButtonDaftarDokter.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonDaftarDokter.setText("Daftar Dokter");
        ButtonDaftarDokter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDaftarDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarDokterActionPerformed(evt);
            }
        });

        ButtonDaftarObat.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonDaftarObat.setText("Daftar Obat");
        ButtonDaftarObat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDaftarObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarObatActionPerformed(evt);
            }
        });

        ButtonDaftarRuangan.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonDaftarRuangan.setText("Daftar Ruangan");
        ButtonDaftarRuangan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDaftarRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarRuanganActionPerformed(evt);
            }
        });

        ButtonPendaftaranPasien.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonPendaftaranPasien.setText("Pendaftaran Pasien");
        ButtonPendaftaranPasien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ButtonPendaftaranDokter.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonPendaftaranDokter.setText("Pendaftaran Dokter");
        ButtonPendaftaranDokter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonPendaftaranDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPendaftaranDokterActionPerformed(evt);
            }
        });

        ButtonPendaftaranObat.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonPendaftaranObat.setText("Pendaftaran Obat");
        ButtonPendaftaranObat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonPendaftaranObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPendaftaranObatActionPerformed(evt);
            }
        });

        ButtonJadwalDokter.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonJadwalDokter.setText("Jadwal Dokter");
        ButtonJadwalDokter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonJadwalDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonJadwalDokterActionPerformed(evt);
            }
        });

        ButtonResepPasien.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonResepPasien.setText("Resep Pasien");
        ButtonResepPasien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonResepPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResepPasienActionPerformed(evt);
            }
        });

        ButtonLogout.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        ButtonLogout.setText("Logout");
        ButtonLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSidebarAdmin2Layout = new javax.swing.GroupLayout(PanelSidebarAdmin2);
        PanelSidebarAdmin2.setLayout(PanelSidebarAdmin2Layout);
        PanelSidebarAdmin2Layout.setHorizontalGroup(
            PanelSidebarAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSidebarAdmin2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelSidebarAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonDaftarPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDaftarDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDaftarObat, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDaftarRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPendaftaranPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPendaftaranDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPendaftaranObat, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonJadwalDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonResepPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PanelSidebarAdmin2Layout.setVerticalGroup(
            PanelSidebarAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSidebarAdmin2Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(ButtonDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarPasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarDokter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarObat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDaftarRuangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPendaftaranPasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPendaftaranDokter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPendaftaranObat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonJadwalDokter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonResepPasien)
                .addGap(34, 34, 34)
                .addComponent(ButtonLogout)
                .addContainerGap(1833, Short.MAX_VALUE))
        );

        LabelPendaftaranPasien.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        LabelPendaftaranPasien.setText("Pendaftaran Pasien");

        LabelMasukkanNama.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        LabelMasukkanNama.setText("Masukkan Nama Pasien :");

        LabelMasukkanAlamat.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        LabelMasukkanAlamat.setText("Masukkan Alamat Pasien :");

        TextareaAlamat.setColumns(20);
        TextareaAlamat.setRows(5);
        jScrollPane1.setViewportView(TextareaAlamat);

        LabelMasukkanAlamat1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        LabelMasukkanAlamat1.setText("Masukkan Telepon Pasien :");

        TextfieldTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfieldTeleponActionPerformed(evt);
            }
        });

        ButtonSendPasien.setBackground(new java.awt.Color(0, 51, 153));
        ButtonSendPasien.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        ButtonSendPasien.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSendPasien.setText("Send");
        ButtonSendPasien.setPreferredSize(new java.awt.Dimension(100, 35));
        ButtonSendPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSendPasienActionPerformed(evt);
            }
        });

        LabelMasukkanID.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        LabelMasukkanID.setText("Masukkan ID Pasien :");

        TextfieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfieldIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PanelSidebarAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 187, Short.MAX_VALUE)
                                .addComponent(LabelPendaftaranPasien)
                                .addGap(185, 185, 185))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(LabelMasukkanAlamat1)
                                        .addComponent(TextfieldNama, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                                        .addComponent(LabelMasukkanNama)
                                        .addComponent(LabelMasukkanAlamat)
                                        .addComponent(jScrollPane1)
                                        .addComponent(TextfieldTelepon)
                                        .addComponent(TextfieldID))
                                    .addComponent(LabelMasukkanID))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(ButtonSendPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PanelSidebarAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 2327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(LabelPendaftaranPasien)
                .addGap(24, 24, 24)
                .addComponent(LabelMasukkanID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextfieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelMasukkanNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextfieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelMasukkanAlamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelMasukkanAlamat1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextfieldTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ButtonSendPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDashboardActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini (DaftarPasienAdmin)
        this.dispose();

        // 2. Buka form DashboardAdmin
        DashboardAdmin dashboard = new DashboardAdmin();
        dashboard.setVisible(true);
    }//GEN-LAST:event_ButtonDashboardActionPerformed

    private void ButtonDaftarPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarPasienActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini (DaftarPasienAdmin)
        this.dispose();

        // 2. Buka form DaftarPasien
        DaftarPasienAdmin daftarpasien = new DaftarPasienAdmin();
        daftarpasien.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarPasienActionPerformed

    private void ButtonDaftarDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarDokterActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini (DaftarPasienAdmin)
        this.dispose();

        // 2. Buka form DaftarPasien
        DaftarDokterAdmin daftardokter = new DaftarDokterAdmin();
        daftardokter.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarDokterActionPerformed

    private void ButtonDaftarObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarObatActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        DaftarObatAdmin daftarobat = new DaftarObatAdmin();
        daftarobat.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarObatActionPerformed

    private void TextfieldTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfieldTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextfieldTeleponActionPerformed

    private void ButtonDaftarRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarRuanganActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
    this.dispose();
    
    // 2. Buka form 
    DaftarRuanganAdmin daftarruangan = new DaftarRuanganAdmin();
    daftarruangan.setVisible(true);
    }//GEN-LAST:event_ButtonDaftarRuanganActionPerformed

    private void ButtonSendPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSendPasienActionPerformed
        // TODO add your handling code here:
try {
    String id = TextfieldID.getText().trim();
    String nama = TextfieldNama.getText().trim();
    String alamat = TextareaAlamat.getText().trim();
    String telepon = TextfieldTelepon.getText().trim();

    // Validasi input
    if (id.isEmpty() || nama.isEmpty() || alamat.isEmpty() || telepon.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    PasienController pc = new PasienController();
    pc.tambahPasien(id, nama, alamat, telepon);

    JOptionPane.showMessageDialog(this, "Data pasien berhasil disimpan!");

    // Reset form
    TextfieldID.setText("");
    TextfieldNama.setText("");
    TextareaAlamat.setText("");
    TextfieldTelepon.setText("");

} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Gagal menyimpan data pasien.\n" + ex.getMessage());
}


    }//GEN-LAST:event_ButtonSendPasienActionPerformed

    private void TextfieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextfieldIDActionPerformed

    private void ButtonPendaftaranDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPendaftaranDokterActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        PendaftaranDokterAdmin daftardokter = new PendaftaranDokterAdmin();
        daftardokter.setVisible(true);
    }//GEN-LAST:event_ButtonPendaftaranDokterActionPerformed

    private void ButtonPendaftaranObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPendaftaranObatActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        PendaftaranObatAdmin daftarobat = new PendaftaranObatAdmin();
        daftarobat.setVisible(true);
    }//GEN-LAST:event_ButtonPendaftaranObatActionPerformed

    private void ButtonJadwalDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonJadwalDokterActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        JadwalDokterAdmin daftarjadwal = new JadwalDokterAdmin();
        daftarjadwal.setVisible(true);
    }//GEN-LAST:event_ButtonJadwalDokterActionPerformed

    private void ButtonResepPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResepPasienActionPerformed
        // TODO add your handling code here:
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form
        ResepPasienAdmin daftarresep = new ResepPasienAdmin();
        daftarresep.setVisible(true);
    }//GEN-LAST:event_ButtonResepPasienActionPerformed

    private void ButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogoutActionPerformed
        // TODO add your handling code here:
        // Tampilkan dialog konfirmasi
    int pilihan = JOptionPane.showConfirmDialog(this, 
                    "Apakah Anda yakin ingin logout?", 
                    "Konfirmasi Logout", 
                    JOptionPane.YES_NO_OPTION);

    // Jika pengguna memilih "Yes"
    if (pilihan == JOptionPane.YES_OPTION) {
        // 1. Tutup form saat ini
        this.dispose();

        // 2. Buka form login
        Login login = new Login();
        login.setVisible(true);
      }
    }//GEN-LAST:event_ButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendaftaranPasienAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendaftaranPasienAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendaftaranPasienAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendaftaranPasienAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendaftaranPasienAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDaftarDokter;
    private javax.swing.JButton ButtonDaftarObat;
    private javax.swing.JButton ButtonDaftarPasien;
    private javax.swing.JButton ButtonDaftarRuangan;
    private javax.swing.JButton ButtonDashboard;
    private javax.swing.JButton ButtonJadwalDokter;
    private javax.swing.JButton ButtonLogout;
    private javax.swing.JButton ButtonPendaftaranDokter;
    private javax.swing.JButton ButtonPendaftaranObat;
    private javax.swing.JButton ButtonPendaftaranPasien;
    private javax.swing.JButton ButtonResepPasien;
    private javax.swing.JButton ButtonSendPasien;
    private javax.swing.JLabel LabelMasukkanAlamat;
    private javax.swing.JLabel LabelMasukkanAlamat1;
    private javax.swing.JLabel LabelMasukkanID;
    private javax.swing.JLabel LabelMasukkanNama;
    private javax.swing.JLabel LabelPendaftaranPasien;
    private javax.swing.JPanel PanelSidebarAdmin2;
    private javax.swing.JTextArea TextareaAlamat;
    private javax.swing.JTextField TextfieldID;
    private javax.swing.JTextField TextfieldNama;
    private javax.swing.JTextField TextfieldTelepon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
